/// DNS and network-layer security monitoring.
///
/// Detects:
/// - /etc/hosts file tampering (T1565.001 — Data Manipulation: Stored Data Manipulation)
/// - Domain Generation Algorithm (DGA) patterns in network connections
/// - DNS tunneling patterns (T1071.004)
///
/// macOS user-space limitation: We cannot directly intercept DNS queries without
/// a Network System Extension. Instead, we monitor /etc/hosts for unauthorized
/// modifications (a common attacker tactic to redirect traffic) and provide DGA
/// analysis utilities that can be called on domains observed in network telemetry.
use crate::models::{AlertSeverity, TelemetryEvent};
use crate::entropy::shannon_entropy;
use chrono::{DateTime, Utc};
use serde_json::json;
use sha2::{Digest, Sha256};

pub struct DnsMonitor {
    /// SHA256 of /etc/hosts content at last check. None means not yet initialized.
    hosts_hash: Option<String>,
}

impl DnsMonitor {
    pub fn new() -> Self {
        Self { hosts_hash: None }
    }

    /// Poll /etc/hosts for modification.
    /// On the first call, baselines the current content silently.
    /// On subsequent calls, emits an alert if the content has changed.
    pub fn check_and_update(&mut self, now: DateTime<Utc>) -> Vec<TelemetryEvent> {
        let mut events = Vec::new();

        if let Some(event) = self.check_hosts_tampering(now) {
            events.push(event);
        }

        events
    }

    fn check_hosts_tampering(&mut self, now: DateTime<Utc>) -> Option<TelemetryEvent> {
        let current_hash = hash_file_contents("/etc/hosts")?;

        match &self.hosts_hash {
            None => {
                // First call — baseline silently
                self.hosts_hash = Some(current_hash);
                None
            }
            Some(known) if known == &current_hash => None,
            Some(_) => {
                // /etc/hosts content changed since last check
                self.hosts_hash = Some(current_hash);
                Some(TelemetryEvent::alert(
                    now,
                    "alert_hosts_file_tampered",
                    AlertSeverity::High,
                    "/etc/hosts was modified — possible DNS hijacking or C2 redirection",
                    json!({
                        "path": "/etc/hosts",
                        "mitre_technique": "T1565.001",
                        "category": "defense_evasion",
                        "confidence": "high",
                        "reason": "/etc/hosts content changed — attacker may be redirecting DNS queries to malicious IP addresses",
                        "details": {
                            "path": "/etc/hosts",
                            "mitre_technique": "T1565.001",
                        }
                    }),
                ))
            }
        }
    }

    /// Heuristic check: does this domain look like it was generated by a
    /// Domain Generation Algorithm (DGA)?
    ///
    /// DGA domains are algorithmically generated to evade IP-based C2 blocklists.
    /// They tend to have high character entropy and random-looking hostnames.
    ///
    /// False-positive rate: moderate. Use this as a contributing signal rather
    /// than a standalone detection.
    pub fn is_likely_dga(domain: &str) -> bool {
        let parts: Vec<&str> = domain.split('.').collect();
        if parts.len() < 2 {
            return false;
        }

        let hostname = parts[0];
        // Very short hostnames are not DGA (api, www, mail, etc.)
        if hostname.len() < 8 {
            return false;
        }
        // Known legitimate short-form prefixes
        if matches!(
            hostname,
            "www" | "api" | "mail" | "smtp" | "imap" | "pop3" | "ftp" | "cdn"
        ) {
            return false;
        }

        let entropy = shannon_entropy(hostname.as_bytes());
        let digit_count = hostname
            .chars()
            .filter(|c| c.is_ascii_digit())
            .count();
        let digit_ratio = digit_count as f64 / hostname.len() as f64;

        // High character entropy indicates randomness (not human-readable words)
        // High digit ratio is another DGA tell (e.g. a7f3b9c2d1.example.com)
        entropy > 3.8 || digit_ratio > 0.33
    }

    /// Check if a domain shows signs of DNS tunneling.
    ///
    /// DNS tunneling encodes data in DNS query labels to exfiltrate data or
    /// establish C2 channels over DNS (T1071.004). Tunneling tools typically
    /// use very long subdomain labels or many subdomains.
    pub fn is_likely_tunneling(domain: &str) -> bool {
        let parts: Vec<&str> = domain.split('.').collect();
        // DNS tunneling requires labels > 50 chars or unusual nesting
        parts.iter().any(|part| part.len() > 50)
            || domain.len() > 200
            || parts.len() > 8
    }
}

fn hash_file_contents(path: &str) -> Option<String> {
    let content = std::fs::read(path).ok()?;
    let hash = Sha256::digest(&content);
    Some(format!("{:x}", hash))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dga_detection_rejects_short_hostname() {
        assert!(!DnsMonitor::is_likely_dga("api.example.com"));
        assert!(!DnsMonitor::is_likely_dga("www.google.com"));
    }

    #[test]
    fn dga_detection_flags_random_hostname() {
        // Random-looking DGA domain: high entropy hostname
        assert!(DnsMonitor::is_likely_dga("x7k2m9p4q1r8s5t3.example.com"));
    }

    #[test]
    fn tunneling_detection_flags_long_label() {
        let long_label = format!(
            "{}.example.com",
            "a".repeat(60)
        );
        assert!(DnsMonitor::is_likely_tunneling(&long_label));
    }

    #[test]
    fn tunneling_detection_flags_deep_nesting() {
        assert!(DnsMonitor::is_likely_tunneling(
            "a.b.c.d.e.f.g.h.i.example.com"
        ));
    }

    #[test]
    fn tunneling_detection_passes_normal_domain() {
        assert!(!DnsMonitor::is_likely_tunneling("api.example.com"));
        assert!(!DnsMonitor::is_likely_tunneling("subdomain.internal.corp.com"));
    }

    #[test]
    fn hosts_monitor_baselines_silently_on_first_call() {
        let mut monitor = DnsMonitor::new();
        // /etc/hosts exists on every macOS system
        let now = chrono::Utc::now();
        let events = monitor.check_and_update(now);
        assert!(events.is_empty(), "first call should baseline silently");
    }

    #[test]
    fn hosts_monitor_no_alert_when_unchanged() {
        let mut monitor = DnsMonitor::new();
        let now = chrono::Utc::now();
        monitor.check_and_update(now); // baseline
        let events = monitor.check_and_update(now); // second call — unchanged
        assert!(events.is_empty(), "unchanged /etc/hosts should not alert");
    }
}
